name: Check
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Install deps
                run: npm ci
            -   name: test
                run: npm test