name: CI/CD Pipeline
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Install dependencies
                run: npm ci
            -   name: Run tests
                run: npm test
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Build and push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: dufi1928/mon-app-de-biere:latest
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Deploy to Docker Swarm
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST_MANAGER }}
                    username: ${{ secrets.MANA_USERNAME }}
                    key: ${{ secrets.MANA_SSH }}
                    script: |
                        SERVICE_NAME=my-next-app
                        IMAGE_NAME=dufi1928/mon-app-de-biere:latest
                        SERVICE_EXISTS=$(docker service ls | grep $SERVICE_NAME || true)
                        if [ -z "$SERVICE_EXISTS" ]; then
                            echo "Creating new service my-next-app"
                            docker service create --name $SERVICE_NAME --replicas 1 --publish published=80,target=80 $IMAGE_NAME
                        else
                            echo "Service my-next-app already exists, updating..."
                            docker service update --image $IMAGE_NAME $SERVICE_NAME
                        fi